PUT http://proyecto-final-sv.herokuapp.com/api/productos/63407ef052570f308f4d84ec HTTP/1.1
content-type: application/json

{
    "precio": 0,
    "nombre": "aHOLA",
    "codigo": "12312412",
    "precio": 156464,
    "stock": 1,
    "thumbnail":"asd",
    "__v": 0
}