GET http://proyecto-final-sv.herokuapp.com/api/logout HTTP/1.1
content-type: application/json

{
    "nombre": "sfaf",
    "apellido": "hola",
    "email": "qwe@yahoo.com",
    "password": "asdasd12",
    "imagen":"asd"
}